### ISSUE TITLE
Build fails with "Could not resolve dependencies"

### ISSUE THREAD

**Issue by matpab** [OpenEndpoints/endpoints#10]
Building with `mvn clean package` fails with following error message

`
[ERROR] Failed to execute goal on project endpoints: Could not resolve dependencies for project com.offerready:endpoints:war:1.0.0-SNAPSHOT: The following artifacts could not be resolved: com.databasesandlife:java-common:jar:17.0.0, com.offerready:xslt-library:jar:5.0.0: Could not find artifact com.databasesandlife:java-common:jar:17.0.0 in clojars (https://clojars.org/repo/) -> [Help 1]
`

**Comment by dev-offer-ready** [comment]
Thanks for the report, I know the reason for this, I'll fix this within the next few days.

**Comment by matpab** [comment]
Thanks for the effort. Unfortunately the command still fails with `[ERROR] Failed to execute goal on project endpoints: Could not resolve dependencies for project com.offerready:endpoints:war:1.0.0-SNAPSHOT: Could not find artifact com.offerready:xslt-library:jar:5.0.0 in clojars (https://clojars.org/repo/) -> [Help 1]
`

**Comment by dev-offer-ready** [comment]
Thanks for the report. I shall look at this and get back to you.

**Comment by matpab** [comment]
The error disappeared after your deletion of the repositories in the pom.xml

**Comment by dev-offer-ready** [comment]
Great. Independently of the pom.xml changes, I uploaded the necessary dependencies to Maven Central. But they haven't turned up on their website yet (it takes a few hours). I guess they're available to Maven even if they're not on the website yet.

I have also changed our deployment procedure to try to stop this sort of thing happening again.
